services:
    _defaults:
        autowire: true

    Kutny\ControllerExtraBundle\AnnotationListPreparer:

    Kutny\ControllerExtraBundle\BeforeAction\BeforeActionResolver:
        arguments:
            - '@service_container'

    Kutny\ControllerExtraBundle\ControllerActionIdentificationParser:

    Kutny\ControllerExtraBundle\ParamConverter\ParamConverterResolver:
        arguments:
            - '@service_container'

    Kutny\ControllerExtraBundle\RequestAfterSecurityListener:
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    Kutny\ControllerExtraBundle\RequestBeforeSecurityListener:
        arguments:
            - '@service_container'
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 8}
